//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktaking
{
    using System;
    using System.Collections.Generic;
    
    public partial class konto
    {
        public konto()
        {
            this.raport = new HashSet<raport>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public byte[] haslo { get; set; }
        public int konto_typ_id { get; set; }
        public int pracownik_id { get; set; }
    
        public virtual konto_typ konto_typ { get; set; }
        public virtual pracownik pracownik { get; set; }
        public virtual ICollection<raport> raport { get; set; }
    }
}
