//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktaking
{
    using System;
    using System.Collections.Generic;
    
    public partial class pracownik
    {
        public pracownik()
        {
            this.konto = new HashSet<konto>();
            this.zaklad = new HashSet<zaklad>();
        }
    
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<int> sala_id { get; set; }
    
        public virtual ICollection<konto> konto { get; set; }
        public virtual sala sala { get; set; }
        public virtual ICollection<zaklad> zaklad { get; set; }
    }
}
