//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktaking
{
    using System;
    using System.Collections.Generic;
    
    public partial class raport
    {
        public int id { get; set; }
        public System.DateTime data { get; set; }
        public string raport1 { get; set; }
        public Nullable<int> konto_id { get; set; }
        public string imie_nazwisko { get; set; }
    
        public virtual konto konto { get; set; }
    }
}
