//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktaking
{
    using System;
    using System.Collections.Generic;
    
    public partial class sala
    {
        public sala()
        {
            this.pracownik = new HashSet<pracownik>();
            this.sprzet = new HashSet<sprzet>();
        }
    
        public int id { get; set; }
        public int numer { get; set; }
        public int pojemnosc { get; set; }
        public int sala_typ_id { get; set; }
        public Nullable<int> zaklad_id { get; set; }
    
        public virtual ICollection<pracownik> pracownik { get; set; }
        public virtual sala_typ sala_typ { get; set; }
        public virtual zaklad zaklad { get; set; }
        public virtual ICollection<sprzet> sprzet { get; set; }
    }
}
