//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktaking
{
    using System;
    using System.Collections.Generic;
    
    public partial class sala_typ
    {
        public sala_typ()
        {
            this.sala = new HashSet<sala>();
        }
    
        public int id { get; set; }
        public string typ_sali { get; set; }
    
        public virtual ICollection<sala> sala { get; set; }
    }
}
