//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktaking
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprzet
    {
        public int id { get; set; }
        public string opis { get; set; }
        public int sprzet_typ_id { get; set; }
        public int sala_id { get; set; }
    
        public virtual sala sala { get; set; }
        public virtual sprzet_typ sprzet_typ { get; set; }
    }
}
