//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stocktaking
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprzet_typ
    {
        public sprzet_typ()
        {
            this.sprzet = new HashSet<sprzet>();
        }
    
        public int id { get; set; }
        public string typ_sprzetu { get; set; }
    
        public virtual ICollection<sprzet> sprzet { get; set; }
    }
}
